name: Run Preprocessing

on:
  push:
    branches:
      - main   # jalan setiap ada push ke branch main
  workflow_dispatch: # bisa dijalankan manual dari GitHub Actions tab

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Jasmein_Al-baar.py
